# Generated by Django 5.0.2 on 2024-04-24 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name': 'Поиск', 'verbose_name_plural': 'Поиск'},
        ),
        migrations.AlterModelTable(
            name='search',
            table='search',
        ),
    ]
