# Generated by Django 4.2.7 on 2024-03-14 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_filter_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter_test',
            name='product',
            field=models.ForeignKey(limit_choices_to={'category_name': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.categories', to_field='name', verbose_name='Категория')}, on_delete=django.db.models.deletion.CASCADE, to='goods.products', verbose_name='Продукт'),
        ),
    ]
