# Generated by Django 5.0.2 on 2024-04-22 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0015_alter_filter_test_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter_test',
            name='name',
            field=models.CharField(default='TEST', max_length=150, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='filter_test',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.products', verbose_name='Продукт'),
        ),
    ]
