# Generated by Django 5.0.2 on 2024-04-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0016_filter_test_name_alter_filter_test_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter_test',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название'),
        ),
    ]
